### ISSUE TITLE
Leaflet marker displays duplicate icon

### ISSUE THREAD

**Issue by julius91** [JeroenDeDauw/Maps#607]
### Setup

- Maps version: 7.15.6
- MW version:1.34.0
- PHP version: 7.4.3
- SMW version (if applicable): 3.1.5

### Issue
Seems related to #477
When displaying any map using the default Leaflet service, the primary marker is "shadowed" by a stretched duplicate marker. Mouse-over changes only over the primary marker. The secondary distorted marker seems to be only visual.
![screenshot_11](https://user-images.githubusercontent.com/62098559/76514021-3fa9be80-647d-11ea-82ae-715420a5c432.png)

```
{{#display_map:New Delhi}}
```

#### Steps to reproduce the observation
* upgraded entire wiki last weekend and installed all extensions fresh
* all maps-related preferences are in default
* no changes to maps/ directory

**Comment by JeroenDeDauw** [comment]
I this publicly accessible?

**Comment by julius91** [comment]
@JeroenDeDauw I'm afraid not.

**Comment by PeterTheOne** [comment]
@julius91 which browser did you use? Please try another one and check if it still behaves the same.

**Comment by julius91** [comment]
@PeterTheOne firefox and chrome show same problem

**Comment by julius91** [comment]
I have just done some debugging, and it seems this issue is related to images cache (see screenshots). The "marker-shadow" gets replaced by "marker" from cache and resized. What do you think?
![screenshot_12](https://user-images.githubusercontent.com/62098559/76674854-c07dcd00-65d9-11ea-9c4d-e07a231cdfac.png)
![screenshot_13](https://user-images.githubusercontent.com/62098559/76674856-c2479080-65d9-11ea-93a6-c96e27a0122b.png)

**Comment by JeroenDeDauw** [comment]
I never fully pinned down the issue in the older version of Maps. It seems that somehow MediaWiki's Resource Loader fucks up these images. I fixed the issue by loading the core Leaflet library outside of Resource Loader. That seemed to have worked everywhere, so not sure why this is showing up on one specific wiki now.

@julius91 I'll have a look at the link you mailed me tomorrow

**Comment by JeroenDeDauw** [comment]
My guess is that you are doing some non-standard caching on your wiki. The image URL you have on your site is `/images/marker-icon.png?2273e")marker-icon.png` while on others it is just `/images/marker-icon.png`.

Anything non standard that you did come to mind?

**Comment by julius91** [comment]
@JeroenDeDauw Nope. No special caching and . I don't know where this is coming from. This is what I just did to confirm:
1. I disabled cache ```$wgMainCacheType = CACHE_NONE; // previously CACHE_ACCEL;```
2. cleared cache by emptying the cache directory
3. ran my browser in debug mode with "disable cache"
4. changed PHP from 7.4 -> 7.3.15 (no special settings either)
5. no difference: the icons still have the "?2273e" suffix and behaviour as before.

Any ideas?

**Comment by akuckartz** [comment]
@julius91 No Apache http server or something similar?

**Comment by julius91** [comment]
@akuckartz I am running wiki on apache 2.4.41 but there is no caching enabled for wiki from apache side. I checked the list of enabled modules and also the config files. No mention of any caching. Only cache related module is "socache_shmcb", but this is required for SSL and I don't think it meddles with the images.

I am open to suggestions.

**Comment by JeroenDeDauw** [comment]
I suggest you ask on the MediaWiki mailing list https://lists.wikimedia.org/mailman/listinfo/mediawiki-l. If you describe the unexpected URL someone might be able to identify what is going on.

**Comment by julius91** [comment]
Thanks for that tip. I posted on the mailing list.

**Comment by julius91** [comment]
Hi guys, I got a response on the mailing list. 

——————
Question: Where does the hash come from?
Answer: The ResourceLoader adds the hash.

*Problem Example:* maps extension needs two icons: marker-icon.png,
marker-shadow.png. The browser loads:
"marker-icon.png?2273e%22)marker-icon.png" and
"marker-icon.png?2273e%22)marker-shadow.png", but both files end up looking
like "marker-icon.png" image.

Answer: The question mark starts the query string, so the filename is everything
before the question mark, so in this case they are the same files.
————


Any ideas where to go from here?

**Comment by JeroenDeDauw** [comment]
In that case the question becomes why on your wiki the resource loader file is used, while on others the "plain loaded" one is.

Maps is loading the core files of Leaflet twice. Once via resource loader and once via "plain HTML". It's weird to do this. Originally they where just loaded via resource loader. This resulted in the bug you are looking at happening everywhere. I tried switching to just plain loading, but this did not work. Hence the combination.

I do not know why Resource Loader breaks the Leaflet library. 

---

You could use a custom marker instead of the default one. There is currently no config to do this wiki wide, though you can do it on a map-wide bases with the icon parameter: https://www.semantic-mediawiki.org/wiki/Extension:Maps/Leaflet

Another alternative is to switch to using Google Maps instead of Leaflet.

Or you can try get answers to why Resource Loader is breaking Leaflet in this extension from people that know more about its inner workings. For instance on the mailing list.

A final option is that if funding is available I can spend more time on this.

**Comment by julius91** [comment]
Now the problem has popped up in the semantic project wiki. Interestingly it is working without resource loader complications in the "Extension" namespace, but throws the same faulty behaivour in the "Help" namespace. Maybe the semantic team is interested in investigating the matter?

(same bug)      https://www.semantic-mediawiki.org/wiki/Help:Leaflet_format
(working well)  https://www.semantic-mediawiki.org/wiki/Extension:Maps/Displaying_maps#Markers

____________________________
@JeroenDeDauw Thank you for all this information. I really appreciate your support and the work you do. I will use custom icon as suggested until new release will hopefully fix this for me as well.

**Comment by JeroenDeDauw** [comment]
I refreshed the cache of https://www.semantic-mediawiki.org/wiki/Help:Leaflet_format and now it works fine as well. I hope it still was cached from back when the bug was everywhere and that this is not some intermittent defect.

**Comment by julius91** [comment]
> I refreshed the cache of https://www.semantic-mediawiki.org/wiki/Help:Leaflet_format and now it works fine as well. I hope it still was cached from back when the bug was everywhere and that this is not some intermittent defect.

Good!

**Comment by mwjames** [comment]
### Setup and configuration

```
{
    "SMWSQLStore": {
        "mysql": "10.4.11-MariaDB"
    },
    "smw": "3.2.0-alpha",
    "mediawiki": "1.34.0",
    "php": "7.4.1"
}
```

Maps | 7.15.6

## Issue

I found the same issue where a "shadow" image is shown next to the marker icon.

![image](https://user-images.githubusercontent.com/1245473/77044754-54e59680-6a03-11ea-9158-2cb3a0d884f2.png)

By looking at the HTML, one can see a `leaflet-shadow-pane` and when manipulating the CSS manually the "shadow" image is separated from the original marker-icon. So, it is unclear why `leaflet-shadow-pane` is generated even though a normal marker icon exits.

![image](https://user-images.githubusercontent.com/1245473/77044771-5ca53b00-6a03-11ea-80c0-0e88054da9b3.png)

**Comment by krabina** [comment]
can also confirm this, seams to be a MW 1.34 issue since with the same maps version this does not happen im MW 1.31

MediaWiki | 1.34.1
-- | --
PHP | 7.3.16 (fpm-fcgi)
MySQL | 8.0.18
ICU | 66.1
Maps: 7.15.6 (4c3b0f1) 15:21, 9 February 2020

**Comment by JeroenDeDauw** [comment]
Oh no. Why did I upgrade to 1.34 one day before giving a presentation? Now I have to fix this issue :D uuuh

**Comment by JeroenDeDauw** [comment]
Definitely resource loader is part of the problem. If I put `$wgResourceLoaderDebug = true`, the issue vanishes.

**Comment by JeroenDeDauw** [comment]
Now also reported on Phabricator https://phabricator.wikimedia.org/T249129

**Comment by JeroenDeDauw** [comment]
I have the impression the issue is fixed with this simple change: https://github.com/JeroenDeDauw/Maps/commit/b6abedd7ad4a7efce80b0e43da5963bcc5ede3a2 (not using Resource Loader at all for leaflet.css).

I thought I already tried that way back when the issue showed up in older MediaWiki versions and that it did not work. So perhaps the change I just made is breaking ... something? 

Feedback is very welcome. You can try running the latest development version of Maps or just make the linked change yourself to whatever version you have. Does everything work fine?

**Comment by julius91** [comment]
@JeroenDeDauw I manually applied the fix you committed and now it is working without problems. Thanks!
